<a href="https://colab.research.google.com/github/yadavsneha17/tops-numpy-assignment/blob/main/Session_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Task 1
zomato = np.array([4.5, 4.0, 3.5, 4.2, 5.0])
swiggy = np.array([4.0, 3.8, 4.5, 4.1, 4.7])
result = np.concatenate((zomato, swiggy))
print(result)

[4.5 4.  3.5 4.2 5.  4.  3.8 4.5 4.1 4.7]


In [3]:
# Task 2
post1 = np.array([100, 200, 150, 300, 250, 180, 220])
post2 = np.array([150, 250, 200, 350, 300, 220, 280])
post3 = np.array([80, 120, 180, 200, 250, 300, 350])

result = np.vstack((post1, post2, post3))
print(result)

[[100 200 150 300 250 180 220]
 [150 250 200 350 300 220 280]
 [ 80 120 180 200 250 300 350]]


In [4]:
# Task 3
import numpy as np
ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112])
parts = np.array_split(ids, 5)
print(parts)

[array([101, 102, 103]), array([104, 105, 106]), array([107, 108]), array([109, 110]), array([111, 112])]


In [5]:
# Task 4
messages = np.array([
    [10, 20, 15, 12, 18, 20, 25],
    [5, 8, 10, 7, 6, 9, 11],
    [30, 25, 28, 35, 32, 30, 40]
])

new_user = np.array([[15, 18, 20, 16, 22, 19, 25]])
messages = np.insert(messages, 3, new_user, axis=0)
least = np.argmin(messages.sum(axis=1))
messages = np.delete(messages, least, axis=0)
print(messages)

[[10 20 15 12 18 20 25]
 [30 25 28 35 32 30 40]
 [15 18 20 16 22 19 25]]


In [6]:
# Task 5
views = np.array([1000, 2000, 3000])
view_array = views.view()
copy_array = views.copy()
view_array[0] = 5000
copy_array[0] = 9000
print("Original:", views)
print("View:", view_array)
print("Copy:", copy_array)

Original: [5000 2000 3000]
View: [5000 2000 3000]
Copy: [9000 2000 3000]
