<a href="https://colab.research.google.com/github/yadavsneha17/tops-numpy-assignment/blob/main/Session_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Task 1
import numpy as np
prices = np.array([299, 499, 799, 0, 1599, -1, 899])
print(prices)
print(prices.dtype)

[ 299  499  799    0 1599   -1  899]
int64


In [3]:
# Task 2
positive = prices[prices > 0]
average = positive.mean()
prices[prices <= 0] = average
print(prices)

[ 299  499  799  819 1599  819  899]


In [4]:
# Task 3
quantities = np.array([2, 1, 3, 4, 2, 1, 5])
total_bill = prices * quantities
print(total_bill)

[ 598  499 2397 3276 3198  819 4495]


In [5]:
# Task 4
print("Minimum:", prices.min())
print("Maximum:", prices.max())
print("Average:", prices.mean())
print("Total:", prices.sum())
print("Total Bill:", total_bill.sum())

Minimum: 299
Maximum: 1599
Average: 819.0
Total: 5733
Total Bill: 15282


In [6]:
# Task 5
unique_prices = np.unique(prices)

print("Unique prices:", unique_prices)
print("Number of unique prices:", len(unique_prices))

Unique prices: [ 299  499  799  819  899 1599]
Number of unique prices: 6
