<a href="https://colab.research.google.com/github/yadavsneha17/tops-numpy-assignment/blob/main/Session_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Task 1
prices = np.array([199, 299, 399, 499, 599])

print("First:", prices[0])
print("Last:", prices[-1])

First: 199
Last: 599


In [3]:
# Task 2
scores = np.array([
    [50, 60, 70, 80, 90],
    [40, 55, 65, 75, 85],
    [30, 45, 60, 70, 80]
])
result = scores[:, 1:4]
print(result)

[[60 70 80]
 [55 65 75]
 [45 60 70]]


In [4]:
# Task 3
ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5])
print(ratings[-3:])

[2.9 5.  3.5]


In [5]:
# Task 4
numbers = np.arange(1, 21)
print(numbers[1::3])

[ 2  5  8 11 14 17 20]


In [6]:
# Task 5
prices = np.array([200, 600, 450, 800, 300, 1000])
result = prices[prices > 500]
print(result)

[ 600  800 1000]


In [7]:
# Task 6
scores = np.array([210, 180, 195, 220, 205, 175])
indices = np.where(scores > 200)
print(indices)

(array([0, 3, 4]),)
