<a href="https://colab.research.google.com/github/yadavsneha17/tops-numpy-assignment/blob/main/Session_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Task 1
teams = np.array(["CSK", "MI", "RCB", "MI", "CSK", "GT", "RCB"])
unique_teams = np.unique(teams)
print(unique_teams)

['CSK' 'GT' 'MI' 'RCB']


In [3]:
# Task 2
ratings = np.array([4.5, np.nan, 4.0, np.nan, 3.5])
missing = np.isnan(ratings)
print("Missing ratings:", np.sum(missing))

Missing ratings: 2


In [4]:
# Task 3
prices = np.array([50, 200, 500, 1200, 800, 1500])
result = np.clip(prices, 100, 1000)
print(result)

[ 100  200  500 1000  800 1000]


In [5]:
#Task 4
views = np.array([1000, 2000, np.nan, 5000, np.inf])
max_value = np.nanmax(views[np.isfinite(views)])
views[np.isnan(views)] = 0
views[np.isinf(views)] = max_value
print(views)

[1000. 2000.    0. 5000. 5000.]


In [6]:
#Task 5
numbers = np.array([1, 2, 4, 7, 8, 10, 13])
even_indices = np.where(numbers % 2 == 0)
print(even_indices)

(array([1, 2, 4, 5]),)
