<a href="https://colab.research.google.com/github/yadavsneha17/tops-numpy-assignment/blob/main/Session_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Task 1
likes = np.array([120, 250, 340, 180, 500, 420, 300])
print(likes.ndim)
print(likes.shape)
print(likes.size)
print(likes.dtype)
print(likes.itemsize)
print(likes.nbytes)

1
(7,)
7
int64
8
56


In [7]:
# Task 2
steps = np.array([[3000,5000],[4000,6000],[3500,5500],[4500,6500],[5000,7000]])
one_d_= steps.reshape(10)
print(one_d)
two_d = one_d.reshape(5,2)
print(two_d)

[3000 5000 4000 6000 3500 5500 4500 6500 5000 7000]
[[3000 5000]
 [4000 6000]
 [3500 5500]
 [4500 6500]
 [5000 7000]]


In [4]:
# Task 3
prices = np.array([120,250,180,300,150,220,100,350,200,275,160,400])
print(prices.ravel())
print(prices.flatten())
prices.resize(3,4)
print(prices)

[120 250 180 300 150 220 100 350 200 275 160 400]
[120 250 180 300 150 220 100 350 200 275 160 400]
[[120 250 180 300]
 [150 220 100 350]
 [200 275 160 400]]


In [5]:
# Task 4
playlist = np.array([[10,5,3],[8,7,4],[12,6,5]])
print(playlist.T)
print(np.transpose(playlist))

[[10  8 12]
 [ 5  7  6]
 [ 3  4  5]]
[[10  8 12]
 [ 5  7  6]
 [ 3  4  5]]


In [6]:
# Task 5
ratings = np.array([4,5,3,4,5,2,4,5,3,4,5,4,3,5,4])
result = ratings.reshape(3,5)
print(result)
print(result.flatten())

[[4 5 3 4 5]
 [2 4 5 3 4]
 [5 4 3 5 4]]
[4 5 3 4 5 2 4 5 3 4 5 4 3 5 4]
